name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: amazoncorretto:17.0.6-alpine3.17

    steps:
    - uses: actions/checkout@v3
    - name: Build the colors Docker image
      run: docker build . --file Dockerfile --tag bhushanpadhye/colors:$(date +%s)
